// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiE88XZZYZ5O-2SRleG18eAoxrRAE8sjM',
    appId: '1:566682909799:web:8df0805243eb80cf0328c2',
    messagingSenderId: '566682909799',
    projectId: 'fasum-aaf9f',
    authDomain: 'fasum-aaf9f.firebaseapp.com',
    databaseURL: 'https://fasum-aaf9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-aaf9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK9QbDpedWRPmUMyq6Y_GjPEWd7mn9od4',
    appId: '1:566682909799:android:b19584fcf01635790328c2',
    messagingSenderId: '566682909799',
    projectId: 'fasum-aaf9f',
    databaseURL: 'https://fasum-aaf9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-aaf9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgEH6EAscXLexYA9-m5-hGeDsQB8koP5I',
    appId: '1:566682909799:ios:eaa6e782bff4c6ba0328c2',
    messagingSenderId: '566682909799',
    projectId: 'fasum-aaf9f',
    databaseURL: 'https://fasum-aaf9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-aaf9f.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgEH6EAscXLexYA9-m5-hGeDsQB8koP5I',
    appId: '1:566682909799:ios:eaa6e782bff4c6ba0328c2',
    messagingSenderId: '566682909799',
    projectId: 'fasum-aaf9f',
    databaseURL: 'https://fasum-aaf9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-aaf9f.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiE88XZZYZ5O-2SRleG18eAoxrRAE8sjM',
    appId: '1:566682909799:web:9124e41962e223350328c2',
    messagingSenderId: '566682909799',
    projectId: 'fasum-aaf9f',
    authDomain: 'fasum-aaf9f.firebaseapp.com',
    databaseURL: 'https://fasum-aaf9f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-aaf9f.firebasestorage.app',
  );

}