// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4B_b4T2jk-Ki6uQQPjcj40Zbts53mgE',
    appId: '1:477083354649:web:3580b285f020d243b70c88',
    messagingSenderId: '477083354649',
    projectId: 'latihan-uas-46cc0',
    authDomain: 'latihan-uas-46cc0.firebaseapp.com',
    databaseURL: 'https://latihan-uas-46cc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan-uas-46cc0.firebasestorage.app',
    measurementId: 'G-X93XYH2DWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsi-QDYsCt14qvK_mGtd2OnMA9e8FtoVg',
    appId: '1:477083354649:android:6df069ae9ec9adb9b70c88',
    messagingSenderId: '477083354649',
    projectId: 'latihan-uas-46cc0',
    databaseURL: 'https://latihan-uas-46cc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan-uas-46cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4YdbEaERGwIKK4lUtEittVVXt5Ju-Vz0',
    appId: '1:477083354649:ios:5ff1225463a0913bb70c88',
    messagingSenderId: '477083354649',
    projectId: 'latihan-uas-46cc0',
    databaseURL: 'https://latihan-uas-46cc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan-uas-46cc0.firebasestorage.app',
    iosBundleId: 'com.example.latihanUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4YdbEaERGwIKK4lUtEittVVXt5Ju-Vz0',
    appId: '1:477083354649:ios:5ff1225463a0913bb70c88',
    messagingSenderId: '477083354649',
    projectId: 'latihan-uas-46cc0',
    databaseURL: 'https://latihan-uas-46cc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan-uas-46cc0.firebasestorage.app',
    iosBundleId: 'com.example.latihanUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb4B_b4T2jk-Ki6uQQPjcj40Zbts53mgE',
    appId: '1:477083354649:web:063d7f28e775ab40b70c88',
    messagingSenderId: '477083354649',
    projectId: 'latihan-uas-46cc0',
    authDomain: 'latihan-uas-46cc0.firebaseapp.com',
    databaseURL: 'https://latihan-uas-46cc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'latihan-uas-46cc0.firebasestorage.app',
    measurementId: 'G-3PRSJ90H3H',
  );

}